version: 0.1

phases:
  install:
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - npm run build
      - serverless deploy
  post_build:
    commands:
      - mv build/* .
artifacts:
  files:
    - index.html
    - static/js/*.js
    - static/css/*.css
    - static/media/*
