CodeBuildProject:
  Type: "AWS::CodeBuild::Project"
  Properties:
    Name: "${self:custom.serviceName}CodeBuild"
    Description: "This codebuild deploys ${self:custom.serviceName}!"
    ServiceRole:
      Fn::GetAtt:
        - CodeBuildRole
        - Arn
    Artifacts:
      Type: CODEPIPELINE
    Environment:
      Type: LINUX_CONTAINER
      Image: "aws/codebuild/nodejs:7.0.0"
      ComputeType: BUILD_GENERAL1_SMALL
    Source:
      Type: CODEPIPELINE
    TimeoutInMinutes: 15

CodeBuildRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - codebuild.amazonaws.com
        Action:
        - "sts:AssumeRole"
    Policies:
    - PolicyName: codebuild-service
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: "*"
          Resource: "*"
        Version: '2012-10-17'
