service: testTemplate
provider:
  name: aws
  runtime: nodejs6.10
  #stage:
    #prod: prod
    #test: test
    #dev: dev
  region: us-east-1
custom:
  serviceName: Template
  lambdaBucket: ${self:custom.serviceName}-test-lambda-bucket
  siteBucketName: tf-template-host-bucket
functions:
  deploy_spa:
    name: Deploy${self:custom.serviceName}Lambda
    handler: services/py/deploy_spa.lambda_handler
    runtime: python2.7
    environment:
      S3_BUCKET: ${self:custom.siteBucketName}
      S3_KEY: ''
resources:
  Resources:
  Outputs:
